import { TCGCategory, TCGProduct, TCGPrice } from '@/types';

export function getMockCategories(): TCGCategory[] {
  return [
    {
      categoryId: 1,
      name: 'Magic',
      displayName: 'Magic: The Gathering',
      modifiedOn: '2024-01-01T00:00:00',
      seoCategoryName: 'magic-the-gathering',
      sealedLabel: 'Sealed',
      nonSealedLabel: 'Singles',
      conditionGuideUrl: 'https://help.tcgplayer.com/hc/en-us/articles/221430307',
      isScannable: true,
      popularity: 1,
    },
    {
      categoryId: 2,
      name: 'Pokemon',
      displayName: 'Pokémon',
      modifiedOn: '2024-01-01T00:00:00',
      seoCategoryName: 'pokemon',
      sealedLabel: 'Sealed',
      nonSealedLabel: 'Singles',
      conditionGuideUrl: 'https://help.tcgplayer.com/hc/en-us/articles/221430307',
      isScannable: true,
      popularity: 2,
    },
    {
      categoryId: 4,
      name: 'YuGiOh',
      displayName: 'Yu-Gi-Oh!',
      modifiedOn: '2024-01-01T00:00:00',
      seoCategoryName: 'yugioh',
      sealedLabel: 'Sealed',
      nonSealedLabel: 'Singles',
      conditionGuideUrl: 'https://help.tcgplayer.com/hc/en-us/articles/221430307',
      isScannable: true,
      popularity: 3,
    },
  ];
}

function placeholder(name: string): string {
  const encoded = encodeURIComponent(name.substring(0, 20));
  return `https://via.placeholder.com/350x490/1e293b/0ea5e9?text=${encoded}`;
}

const MTG_PRODUCTS: TCGProduct[] = [
  {
    productId: 1000,
    name: 'Black Lotus',
    cleanName: 'Black Lotus',
    imageUrl: placeholder('Black Lotus'),
    categoryId: 1,
    groupId: 1,
    url: 'https://www.tcgplayer.com/product/1000',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Alpha' },
      { name: 'Number', displayName: 'Number', value: '232' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Christopher Rush' },
      { name: 'Type', displayName: 'Type', value: 'Artifact' },
      { name: 'Description', displayName: 'Description', value: '{T}, Sacrifice Black Lotus: Add three mana of any one color.' },
    ],
    customAttributes: { alias: 'black-lotus' },
  },
  {
    productId: 1001,
    name: 'Ancestral Recall',
    cleanName: 'Ancestral Recall',
    imageUrl: placeholder('Ancestral Recall'),
    categoryId: 1,
    groupId: 1,
    url: 'https://www.tcgplayer.com/product/1001',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Alpha' },
      { name: 'Number', displayName: 'Number', value: '47' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Mark Poole' },
      { name: 'Type', displayName: 'Type', value: 'Instant' },
      { name: 'Description', displayName: 'Description', value: 'Target player draws three cards.' },
    ],
    customAttributes: { alias: 'ancestral-recall' },
  },
  {
    productId: 1002,
    name: 'Time Walk',
    cleanName: 'Time Walk',
    imageUrl: placeholder('Time Walk'),
    categoryId: 1,
    groupId: 1,
    url: 'https://www.tcgplayer.com/product/1002',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Alpha' },
      { name: 'Number', displayName: 'Number', value: '85' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Amy Weber' },
      { name: 'Type', displayName: 'Type', value: 'Sorcery' },
      { name: 'Description', displayName: 'Description', value: 'Take an extra turn after this one.' },
    ],
    customAttributes: { alias: 'time-walk' },
  },
  {
    productId: 1003,
    name: 'Mox Sapphire',
    cleanName: 'Mox Sapphire',
    imageUrl: placeholder('Mox Sapphire'),
    categoryId: 1,
    groupId: 1,
    url: 'https://www.tcgplayer.com/product/1003',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Alpha' },
      { name: 'Number', displayName: 'Number', value: '265' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Dan Frazier' },
      { name: 'Type', displayName: 'Type', value: 'Artifact' },
      { name: 'Description', displayName: 'Description', value: '{T}: Add {U}.' },
    ],
    customAttributes: { alias: 'mox-sapphire' },
  },
  {
    productId: 1004,
    name: 'Mox Ruby',
    cleanName: 'Mox Ruby',
    imageUrl: placeholder('Mox Ruby'),
    categoryId: 1,
    groupId: 1,
    url: 'https://www.tcgplayer.com/product/1004',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Alpha' },
      { name: 'Number', displayName: 'Number', value: '264' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Dan Frazier' },
      { name: 'Type', displayName: 'Type', value: 'Artifact' },
      { name: 'Description', displayName: 'Description', value: '{T}: Add {R}.' },
    ],
    customAttributes: { alias: 'mox-ruby' },
  },
  {
    productId: 1005,
    name: 'Underground Sea',
    cleanName: 'Underground Sea',
    imageUrl: placeholder('Underground Sea'),
    categoryId: 1,
    groupId: 1,
    url: 'https://www.tcgplayer.com/product/1005',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Revised' },
      { name: 'Number', displayName: 'Number', value: '287' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Robert Bliss' },
      { name: 'Type', displayName: 'Type', value: 'Land — Island Swamp' },
      { name: 'Description', displayName: 'Description', value: '{T}: Add {U} or {B}.' },
    ],
    customAttributes: { alias: 'underground-sea' },
  },
  {
    productId: 1006,
    name: 'Volcanic Island',
    cleanName: 'Volcanic Island',
    imageUrl: placeholder('Volcanic Island'),
    categoryId: 1,
    groupId: 1,
    url: 'https://www.tcgplayer.com/product/1006',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Revised' },
      { name: 'Number', displayName: 'Number', value: '290' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Jesper Myrfors' },
      { name: 'Type', displayName: 'Type', value: 'Land — Island Mountain' },
      { name: 'Description', displayName: 'Description', value: '{T}: Add {U} or {R}.' },
    ],
    customAttributes: { alias: 'volcanic-island' },
  },
  {
    productId: 1007,
    name: 'Lightning Bolt',
    cleanName: 'Lightning Bolt',
    imageUrl: placeholder('Lightning Bolt'),
    categoryId: 1,
    groupId: 1,
    url: 'https://www.tcgplayer.com/product/1007',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Alpha' },
      { name: 'Number', displayName: 'Number', value: '161' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Common' },
      { name: 'Artist', displayName: 'Artist', value: 'Christopher Rush' },
      { name: 'Type', displayName: 'Type', value: 'Instant' },
      { name: 'Description', displayName: 'Description', value: 'Lightning Bolt deals 3 damage to any target.' },
    ],
    customAttributes: { alias: 'lightning-bolt' },
  },
  {
    productId: 1008,
    name: 'Force of Will',
    cleanName: 'Force of Will',
    imageUrl: placeholder('Force of Will'),
    categoryId: 1,
    groupId: 1,
    url: 'https://www.tcgplayer.com/product/1008',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Alliances' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Common' },
      { name: 'Artist', displayName: 'Artist', value: 'Mark Tedin' },
      { name: 'Type', displayName: 'Type', value: 'Instant' },
      { name: 'Description', displayName: 'Description', value: 'You may pay 1 life and exile a blue card from your hand rather than pay this spell\'s mana cost. Counter target spell.' },
    ],
    customAttributes: { alias: 'force-of-will' },
  },
  {
    productId: 1009,
    name: 'Tarmogoyf',
    cleanName: 'Tarmogoyf',
    imageUrl: placeholder('Tarmogoyf'),
    categoryId: 1,
    groupId: 1,
    url: 'https://www.tcgplayer.com/product/1009',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Future Sight' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Justin Murray' },
      { name: 'Type', displayName: 'Type', value: 'Creature — Lhurgoyf' },
      { name: 'Description', displayName: 'Description', value: "Tarmogoyf's power is equal to the number of card types among cards in all graveyards." },
    ],
    customAttributes: { alias: 'tarmogoyf' },
  },
];

const POKEMON_PRODUCTS: TCGProduct[] = [
  {
    productId: 2000,
    name: 'Charizard (Base Set)',
    cleanName: 'Charizard Base Set',
    imageUrl: placeholder('Charizard'),
    categoryId: 2,
    groupId: 2,
    url: 'https://www.tcgplayer.com/product/2000',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Base Set' },
      { name: 'Number', displayName: 'Number', value: '4/102' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Holo Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Mitsuhiro Arita' },
      { name: 'HP', displayName: 'HP', value: '120' },
      { name: 'Type', displayName: 'Type', value: 'Fire' },
    ],
    customAttributes: { alias: 'charizard-base-set' },
  },
  {
    productId: 2001,
    name: 'Blastoise (Base Set)',
    cleanName: 'Blastoise Base Set',
    imageUrl: placeholder('Blastoise'),
    categoryId: 2,
    groupId: 2,
    url: 'https://www.tcgplayer.com/product/2001',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Base Set' },
      { name: 'Number', displayName: 'Number', value: '2/102' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Holo Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Ken Sugimori' },
      { name: 'HP', displayName: 'HP', value: '100' },
      { name: 'Type', displayName: 'Type', value: 'Water' },
    ],
    customAttributes: { alias: 'blastoise-base-set' },
  },
  {
    productId: 2002,
    name: 'Venusaur (Base Set)',
    cleanName: 'Venusaur Base Set',
    imageUrl: placeholder('Venusaur'),
    categoryId: 2,
    groupId: 2,
    url: 'https://www.tcgplayer.com/product/2002',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Base Set' },
      { name: 'Number', displayName: 'Number', value: '15/102' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Holo Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Mitsuhiro Arita' },
      { name: 'HP', displayName: 'HP', value: '100' },
      { name: 'Type', displayName: 'Type', value: 'Grass' },
    ],
    customAttributes: { alias: 'venusaur-base-set' },
  },
  {
    productId: 2003,
    name: 'Mewtwo (Base Set)',
    cleanName: 'Mewtwo Base Set',
    imageUrl: placeholder('Mewtwo'),
    categoryId: 2,
    groupId: 2,
    url: 'https://www.tcgplayer.com/product/2003',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Base Set' },
      { name: 'Number', displayName: 'Number', value: '10/102' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Holo Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Ken Sugimori' },
      { name: 'HP', displayName: 'HP', value: '60' },
      { name: 'Type', displayName: 'Type', value: 'Psychic' },
    ],
    customAttributes: { alias: 'mewtwo-base-set' },
  },
  {
    productId: 2004,
    name: 'Pikachu (Base Set)',
    cleanName: 'Pikachu Base Set',
    imageUrl: placeholder('Pikachu'),
    categoryId: 2,
    groupId: 2,
    url: 'https://www.tcgplayer.com/product/2004',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Base Set' },
      { name: 'Number', displayName: 'Number', value: '58/102' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Common' },
      { name: 'Artist', displayName: 'Artist', value: 'Mitsuhiro Arita' },
      { name: 'HP', displayName: 'HP', value: '40' },
      { name: 'Type', displayName: 'Type', value: 'Lightning' },
    ],
    customAttributes: { alias: 'pikachu-base-set' },
  },
  {
    productId: 2005,
    name: 'Lugia (Neo Genesis)',
    cleanName: 'Lugia Neo Genesis',
    imageUrl: placeholder('Lugia'),
    categoryId: 2,
    groupId: 2,
    url: 'https://www.tcgplayer.com/product/2005',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Neo Genesis' },
      { name: 'Number', displayName: 'Number', value: '9/111' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Holo Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Hironobu Yoshida' },
      { name: 'HP', displayName: 'HP', value: '90' },
      { name: 'Type', displayName: 'Type', value: 'Colorless' },
    ],
    customAttributes: { alias: 'lugia-neo-genesis' },
  },
  {
    productId: 2006,
    name: 'Gengar (1st Edition)',
    cleanName: 'Gengar 1st Edition',
    imageUrl: placeholder('Gengar'),
    categoryId: 2,
    groupId: 2,
    url: 'https://www.tcgplayer.com/product/2006',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Fossil (1st Edition)' },
      { name: 'Number', displayName: 'Number', value: '5/62' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Holo Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Keiji Kinebuchi' },
      { name: 'HP', displayName: 'HP', value: '80' },
      { name: 'Type', displayName: 'Type', value: 'Psychic' },
    ],
    customAttributes: { alias: 'gengar-1st-edition' },
  },
  {
    productId: 2007,
    name: 'Alakazam (Base Set)',
    cleanName: 'Alakazam Base Set',
    imageUrl: placeholder('Alakazam'),
    categoryId: 2,
    groupId: 2,
    url: 'https://www.tcgplayer.com/product/2007',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Base Set' },
      { name: 'Number', displayName: 'Number', value: '1/102' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Holo Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Ken Sugimori' },
      { name: 'HP', displayName: 'HP', value: '80' },
      { name: 'Type', displayName: 'Type', value: 'Psychic' },
    ],
    customAttributes: { alias: 'alakazam-base-set' },
  },
  {
    productId: 2008,
    name: 'Gyarados (Base Set)',
    cleanName: 'Gyarados Base Set',
    imageUrl: placeholder('Gyarados'),
    categoryId: 2,
    groupId: 2,
    url: 'https://www.tcgplayer.com/product/2008',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Base Set' },
      { name: 'Number', displayName: 'Number', value: '6/102' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Holo Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Mitsuhiro Arita' },
      { name: 'HP', displayName: 'HP', value: '100' },
      { name: 'Type', displayName: 'Type', value: 'Water' },
    ],
    customAttributes: { alias: 'gyarados-base-set' },
  },
  {
    productId: 2009,
    name: 'Rayquaza EX',
    cleanName: 'Rayquaza EX',
    imageUrl: placeholder('Rayquaza EX'),
    categoryId: 2,
    groupId: 2,
    url: 'https://www.tcgplayer.com/product/2009',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Dragon' },
      { name: 'Number', displayName: 'Number', value: '97/97' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Ultra Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Hikaru Koike' },
      { name: 'HP', displayName: 'HP', value: '150' },
      { name: 'Type', displayName: 'Type', value: 'Colorless' },
    ],
    customAttributes: { alias: 'rayquaza-ex' },
  },
];

const YUGIOH_PRODUCTS: TCGProduct[] = [
  {
    productId: 4000,
    name: 'Blue-Eyes White Dragon',
    cleanName: 'Blue-Eyes White Dragon',
    imageUrl: placeholder('Blue-Eyes White Dragon'),
    categoryId: 4,
    groupId: 4,
    url: 'https://www.tcgplayer.com/product/4000',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Legend of Blue Eyes White Dragon' },
      { name: 'Number', displayName: 'Number', value: 'LOB-001' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Ultra Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Kazuki Takahashi' },
      { name: 'Type', displayName: 'Type', value: 'Normal Monster / Dragon' },
      { name: 'ATK/DEF', displayName: 'ATK/DEF', value: '3000 / 2500' },
    ],
    customAttributes: { alias: 'blue-eyes-white-dragon' },
  },
  {
    productId: 4001,
    name: 'Dark Magician',
    cleanName: 'Dark Magician',
    imageUrl: placeholder('Dark Magician'),
    categoryId: 4,
    groupId: 4,
    url: 'https://www.tcgplayer.com/product/4001',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Legend of Blue Eyes White Dragon' },
      { name: 'Number', displayName: 'Number', value: 'LOB-005' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Ultra Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Kazuki Takahashi' },
      { name: 'Type', displayName: 'Type', value: 'Normal Monster / Spellcaster' },
      { name: 'ATK/DEF', displayName: 'ATK/DEF', value: '2500 / 2100' },
    ],
    customAttributes: { alias: 'dark-magician' },
  },
  {
    productId: 4002,
    name: 'Exodia the Forbidden One',
    cleanName: 'Exodia the Forbidden One',
    imageUrl: placeholder('Exodia'),
    categoryId: 4,
    groupId: 4,
    url: 'https://www.tcgplayer.com/product/4002',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Legend of Blue Eyes White Dragon' },
      { name: 'Number', displayName: 'Number', value: 'LOB-124' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Ultra Rare' },
      { name: 'Artist', displayName: 'Artist', value: 'Kazuki Takahashi' },
      { name: 'Type', displayName: 'Type', value: 'Effect Monster / Spellcaster' },
      { name: 'ATK/DEF', displayName: 'ATK/DEF', value: '1000 / 1000' },
    ],
    customAttributes: { alias: 'exodia-the-forbidden-one' },
  },
  {
    productId: 4003,
    name: 'Black Luster Soldier - Envoy of the Beginning',
    cleanName: 'Black Luster Soldier Envoy of the Beginning',
    imageUrl: placeholder('Black Luster Soldier'),
    categoryId: 4,
    groupId: 4,
    url: 'https://www.tcgplayer.com/product/4003',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Invasion of Chaos' },
      { name: 'Number', displayName: 'Number', value: 'IOC-025' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Secret Rare' },
      { name: 'Type', displayName: 'Type', value: 'Effect Monster / Warrior' },
      { name: 'ATK/DEF', displayName: 'ATK/DEF', value: '3000 / 2500' },
    ],
    customAttributes: { alias: 'black-luster-soldier-envoy' },
  },
  {
    productId: 4004,
    name: 'Pot of Greed',
    cleanName: 'Pot of Greed',
    imageUrl: placeholder('Pot of Greed'),
    categoryId: 4,
    groupId: 4,
    url: 'https://www.tcgplayer.com/product/4004',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Legend of Blue Eyes White Dragon' },
      { name: 'Number', displayName: 'Number', value: 'LOB-119' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Rare' },
      { name: 'Type', displayName: 'Type', value: 'Normal Spell' },
      { name: 'Description', displayName: 'Description', value: 'Draw 2 cards.' },
    ],
    customAttributes: { alias: 'pot-of-greed' },
  },
  {
    productId: 4005,
    name: 'Stardust Dragon',
    cleanName: 'Stardust Dragon',
    imageUrl: placeholder('Stardust Dragon'),
    categoryId: 4,
    groupId: 4,
    url: 'https://www.tcgplayer.com/product/4005',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'The Duelist Genesis' },
      { name: 'Number', displayName: 'Number', value: 'TDGS-EN040' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Ultra Rare' },
      { name: 'Type', displayName: 'Type', value: 'Synchro Monster / Dragon' },
      { name: 'ATK/DEF', displayName: 'ATK/DEF', value: '2500 / 2000' },
    ],
    customAttributes: { alias: 'stardust-dragon' },
  },
  {
    productId: 4006,
    name: 'Red-Eyes Black Dragon',
    cleanName: 'Red-Eyes Black Dragon',
    imageUrl: placeholder('Red-Eyes Black Dragon'),
    categoryId: 4,
    groupId: 4,
    url: 'https://www.tcgplayer.com/product/4006',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Legend of Blue Eyes White Dragon' },
      { name: 'Number', displayName: 'Number', value: 'LOB-070' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Ultra Rare' },
      { name: 'Type', displayName: 'Type', value: 'Normal Monster / Dragon' },
      { name: 'ATK/DEF', displayName: 'ATK/DEF', value: '2400 / 2000' },
    ],
    customAttributes: { alias: 'red-eyes-black-dragon' },
  },
  {
    productId: 4007,
    name: 'Trishula, Dragon of the Ice Barrier',
    cleanName: 'Trishula Dragon of the Ice Barrier',
    imageUrl: placeholder('Trishula'),
    categoryId: 4,
    groupId: 4,
    url: 'https://www.tcgplayer.com/product/4007',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Duel Terminal' },
      { name: 'Number', displayName: 'Number', value: 'DT04-EN090' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Duel Terminal Ultra Parallel Rare' },
      { name: 'Type', displayName: 'Type', value: 'Synchro Monster / Dragon' },
      { name: 'ATK/DEF', displayName: 'ATK/DEF', value: '2700 / 2000' },
    ],
    customAttributes: { alias: 'trishula-dragon' },
  },
  {
    productId: 4008,
    name: 'Mirror Force',
    cleanName: 'Mirror Force',
    imageUrl: placeholder('Mirror Force'),
    categoryId: 4,
    groupId: 4,
    url: 'https://www.tcgplayer.com/product/4008',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Metal Raiders' },
      { name: 'Number', displayName: 'Number', value: 'MRD-138' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Ultra Rare' },
      { name: 'Type', displayName: 'Type', value: 'Normal Trap' },
      { name: 'Description', displayName: 'Description', value: 'Destroy all Attack Position monsters your opponent controls.' },
    ],
    customAttributes: { alias: 'mirror-force' },
  },
  {
    productId: 4009,
    name: 'Number 39: Utopia',
    cleanName: 'Number 39 Utopia',
    imageUrl: placeholder('Number 39 Utopia'),
    categoryId: 4,
    groupId: 4,
    url: 'https://www.tcgplayer.com/product/4009',
    modifiedOn: '2024-01-01T00:00:00',
    imageCount: 1,
    presaleInfo: { isPresale: false, releasedOn: null, note: '' },
    extendedData: [
      { name: 'Set', displayName: 'Set', value: 'Starter Deck: Dawn of the Xyz' },
      { name: 'Number', displayName: 'Number', value: 'YS11-EN041' },
      { name: 'Rarity', displayName: 'Rarity', value: 'Ultra Rare' },
      { name: 'Type', displayName: 'Type', value: 'Xyz Monster / Warrior' },
      { name: 'ATK/DEF', displayName: 'ATK/DEF', value: '2500 / 2000' },
    ],
    customAttributes: { alias: 'number-39-utopia' },
  },
];

const ALL_PRODUCTS = [...MTG_PRODUCTS, ...POKEMON_PRODUCTS, ...YUGIOH_PRODUCTS];

const MOCK_PRICES: Record<number, TCGPrice[]> = {
  // MTG Power 9 / Duals
  1000: [{ productId: 1000, lowPrice: 28000, midPrice: 35000, highPrice: 75000, marketPrice: 40000, directLowPrice: 30000, subTypeName: 'Normal' }],
  1001: [{ productId: 1001, lowPrice: 5000, midPrice: 6500, highPrice: 15000, marketPrice: 7200, directLowPrice: 5200, subTypeName: 'Normal' }],
  1002: [{ productId: 1002, lowPrice: 3800, midPrice: 5000, highPrice: 12000, marketPrice: 5500, directLowPrice: 3900, subTypeName: 'Normal' }],
  1003: [{ productId: 1003, lowPrice: 4500, midPrice: 6000, highPrice: 14000, marketPrice: 6800, directLowPrice: 4700, subTypeName: 'Normal' }],
  1004: [{ productId: 1004, lowPrice: 3200, midPrice: 4200, highPrice: 10000, marketPrice: 4800, directLowPrice: 3300, subTypeName: 'Normal' }],
  1005: [
    { productId: 1005, lowPrice: 280, midPrice: 380, highPrice: 650, marketPrice: 390, directLowPrice: 295, subTypeName: 'Normal' },
    { productId: 1005, lowPrice: 320, midPrice: 430, highPrice: 750, marketPrice: 450, directLowPrice: 330, subTypeName: 'Foil' },
  ],
  1006: [
    { productId: 1006, lowPrice: 380, midPrice: 490, highPrice: 800, marketPrice: 510, directLowPrice: 390, subTypeName: 'Normal' },
    { productId: 1006, lowPrice: 420, midPrice: 550, highPrice: 900, marketPrice: 570, directLowPrice: 430, subTypeName: 'Foil' },
  ],
  1007: [
    { productId: 1007, lowPrice: 1.50, midPrice: 2.25, highPrice: 5.00, marketPrice: 2.50, directLowPrice: 1.75, subTypeName: 'Normal' },
    { productId: 1007, lowPrice: 4.00, midPrice: 6.00, highPrice: 15.00, marketPrice: 6.50, directLowPrice: 4.50, subTypeName: 'Foil' },
  ],
  1008: [
    { productId: 1008, lowPrice: 15.00, midPrice: 22.00, highPrice: 45.00, marketPrice: 24.00, directLowPrice: 16.00, subTypeName: 'Normal' },
    { productId: 1008, lowPrice: 25.00, midPrice: 38.00, highPrice: 80.00, marketPrice: 40.00, directLowPrice: 26.00, subTypeName: 'Foil' },
  ],
  1009: [
    { productId: 1009, lowPrice: 25.00, midPrice: 35.00, highPrice: 65.00, marketPrice: 38.00, directLowPrice: 26.00, subTypeName: 'Normal' },
    { productId: 1009, lowPrice: 45.00, midPrice: 65.00, highPrice: 120.00, marketPrice: 70.00, directLowPrice: 47.00, subTypeName: 'Foil' },
  ],
  // Pokemon
  2000: [{ productId: 2000, lowPrice: 2800, midPrice: 4500, highPrice: 12000, marketPrice: 5000, directLowPrice: 2900, subTypeName: 'Normal' }],
  2001: [{ productId: 2001, lowPrice: 200, midPrice: 320, highPrice: 900, marketPrice: 350, directLowPrice: 210, subTypeName: 'Normal' }],
  2002: [{ productId: 2002, lowPrice: 150, midPrice: 240, highPrice: 700, marketPrice: 260, directLowPrice: 160, subTypeName: 'Normal' }],
  2003: [{ productId: 2003, lowPrice: 120, midPrice: 190, highPrice: 550, marketPrice: 200, directLowPrice: 125, subTypeName: 'Normal' }],
  2004: [{ productId: 2004, lowPrice: 8.00, midPrice: 15.00, highPrice: 40.00, marketPrice: 18.00, directLowPrice: 9.00, subTypeName: 'Normal' }],
  2005: [{ productId: 2005, lowPrice: 380, midPrice: 600, highPrice: 1500, marketPrice: 650, directLowPrice: 390, subTypeName: 'Normal' }],
  2006: [{ productId: 2006, lowPrice: 150, midPrice: 250, highPrice: 700, marketPrice: 280, directLowPrice: 160, subTypeName: 'Normal' }],
  2007: [{ productId: 2007, lowPrice: 55, midPrice: 90, highPrice: 250, marketPrice: 95, directLowPrice: 60, subTypeName: 'Normal' }],
  2008: [{ productId: 2008, lowPrice: 60, midPrice: 100, highPrice: 280, marketPrice: 110, directLowPrice: 65, subTypeName: 'Normal' }],
  2009: [{ productId: 2009, lowPrice: 80, midPrice: 130, highPrice: 350, marketPrice: 140, directLowPrice: 85, subTypeName: 'Normal' }],
  // Yu-Gi-Oh
  4000: [
    { productId: 4000, lowPrice: 180, midPrice: 280, highPrice: 700, marketPrice: 300, directLowPrice: 190, subTypeName: 'Normal' },
    { productId: 4000, lowPrice: 250, midPrice: 400, highPrice: 1000, marketPrice: 430, directLowPrice: 260, subTypeName: '1st Edition' },
  ],
  4001: [
    { productId: 4001, lowPrice: 90, midPrice: 140, highPrice: 350, marketPrice: 150, directLowPrice: 95, subTypeName: 'Normal' },
    { productId: 4001, lowPrice: 130, midPrice: 200, highPrice: 500, marketPrice: 220, directLowPrice: 135, subTypeName: '1st Edition' },
  ],
  4002: [
    { productId: 4002, lowPrice: 250, midPrice: 380, highPrice: 950, marketPrice: 400, directLowPrice: 260, subTypeName: 'Normal' },
    { productId: 4002, lowPrice: 350, midPrice: 550, highPrice: 1400, marketPrice: 580, directLowPrice: 360, subTypeName: '1st Edition' },
  ],
  4003: [
    { productId: 4003, lowPrice: 180, midPrice: 280, highPrice: 700, marketPrice: 300, directLowPrice: 190, subTypeName: 'Normal' },
    { productId: 4003, lowPrice: 500, midPrice: 800, highPrice: 2000, marketPrice: 850, directLowPrice: 520, subTypeName: '1st Edition' },
  ],
  4004: [{ productId: 4004, lowPrice: 5.00, midPrice: 8.00, highPrice: 20.00, marketPrice: 9.00, directLowPrice: 5.50, subTypeName: 'Normal' }],
  4005: [
    { productId: 4005, lowPrice: 8.00, midPrice: 14.00, highPrice: 35.00, marketPrice: 15.00, directLowPrice: 8.50, subTypeName: 'Normal' },
    { productId: 4005, lowPrice: 25.00, midPrice: 40.00, highPrice: 100.00, marketPrice: 42.00, directLowPrice: 26.00, subTypeName: '1st Edition' },
  ],
  4006: [
    { productId: 4006, lowPrice: 45, midPrice: 75, highPrice: 200, marketPrice: 80, directLowPrice: 48, subTypeName: 'Normal' },
    { productId: 4006, lowPrice: 120, midPrice: 200, highPrice: 500, marketPrice: 210, directLowPrice: 125, subTypeName: '1st Edition' },
  ],
  4007: [
    { productId: 4007, lowPrice: 30, midPrice: 50, highPrice: 130, marketPrice: 55, directLowPrice: 32, subTypeName: 'Normal' },
    { productId: 4007, lowPrice: 80, midPrice: 130, highPrice: 350, marketPrice: 140, directLowPrice: 85, subTypeName: '1st Edition' },
  ],
  4008: [
    { productId: 4008, lowPrice: 4.00, midPrice: 7.00, highPrice: 18.00, marketPrice: 7.50, directLowPrice: 4.50, subTypeName: 'Normal' },
    { productId: 4008, lowPrice: 15.00, midPrice: 25.00, highPrice: 65.00, marketPrice: 27.00, directLowPrice: 16.00, subTypeName: '1st Edition' },
  ],
  4009: [
    { productId: 4009, lowPrice: 3.00, midPrice: 5.00, highPrice: 12.00, marketPrice: 5.50, directLowPrice: 3.50, subTypeName: 'Normal' },
    { productId: 4009, lowPrice: 8.00, midPrice: 14.00, highPrice: 35.00, marketPrice: 15.00, directLowPrice: 8.50, subTypeName: '1st Edition' },
  ],
};

export function getMockProducts(categoryId?: number, query?: string): TCGProduct[] {
  let products = ALL_PRODUCTS;
  if (categoryId) {
    products = products.filter((p) => p.categoryId === categoryId);
  }
  if (query) {
    const q = query.toLowerCase();
    products = products.filter(
      (p) => p.name.toLowerCase().includes(q) || p.cleanName.toLowerCase().includes(q)
    );
  }
  return products;
}

export function getMockProduct(productId: number): TCGProduct | null {
  return ALL_PRODUCTS.find((p) => p.productId === productId) ?? null;
}

export function getMockPrices(productId: number): TCGPrice[] {
  return MOCK_PRICES[productId] ?? [];
}

export function searchMockProducts(query: string, categoryId?: number): TCGProduct[] {
  const q = query.toLowerCase().trim();
  if (!q) return getMockProducts(categoryId);
  return getMockProducts(categoryId, q);
}
